stages:
  - deploy

deploy:
  stage: deploy
  script:
    - apt-get update && apt-get install -y openssh-client
    - echo "BRUGEREort2023" | sftp -oStrictHostKeyChecking=no -P 22 u2009915384@access914943276.webspace-data.io:/Portfolio/ -b <(echo -e "rm -rf * \n put -r Portfolio/*")
  only:
    - master